_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    IOU_THRESHOLDS: [0.01, 0.3]
    BBOX_REG_LOSS_TYPE: "giou"
    POSITIVE_FRACTION: 0.25
    NMS_THRESH: 0.5
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    IOU_THRESHOLDS: [0.5]
    PROPOSAL_APPEND_GT: True
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.
    LOSS: "FocalLoss"
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    CLS_AGNOSTIC_MASK: False
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (4000,)
  MAX_ITER: 8000
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 2
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 500
DATASETS:
  DEPTH: 3
  STRIDE: 2
  NUMSUPARTERY: 16
  CROSS_DATASET: False
  TRAIN: ("fold1_train",)
  TEST: ("fold1_test",)
INPUT:
  MIN_SIZE_TRAIN: (320,)
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 320
  MAX_SIZE_TEST: 640
  MIN_SIZE_TRAIN_SAMPLING: 'choice'
SEMISUPNET:
  Trainer: "artery"
  BBOX_THRESHOLD: 0.5
  IOU_THRESHOLD: 0.6
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 2000
  EMA_KEEP_RATE: 0.99
  UNSUP_LOSS_WEIGHT: 1.0
TEST:
  EVAL_PERIOD: 500